//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubApplication.Entity
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

	public partial class ClubEntities : DbContext
	{
		private static ClubEntities _ctx;

		public static ClubEntities GetContext()
		{
			if (_ctx == null) _ctx = new ClubEntities();
			return _ctx;
		}
		public ClubEntities()
				: base("name=ClubEntities")
		{
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}

		public virtual DbSet<Child> Children { get; set; }
		public virtual DbSet<Club> Clubs { get; set; }
		public virtual DbSet<Parent> Parents { get; set; }
		public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
		public virtual DbSet<Teacher> Teachers { get; set; }
		public virtual DbSet<User> Users { get; set; }
	}
}
